**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [171]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [172]:
#Code here
null_vector=np.zeros(10)
null_vector[4]=1
null_vector


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [173]:
#Code here
a=int(input('Enter the number '))
b=int(input('enter the second no.'))

gen_random=np.random.random((a,b))
gen_random
gen_random.mean() #avg of arrray 




np.float64(0.4498243739194144)

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [174]:
#Code here

a=np.ones((4,4)   )
a[1:3,1:3]=0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [175]:
#Code here

x=np.linspace(0,1,11,endpoint=False)
x



array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [176]:
#Code here
np.identity(3) #only smme orderlike 3X3 ...etc 
np.eye(3,4) #any order ka idenetity matricx 


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [177]:
#Code here
np.linspace(0,4,25,dtype=int,axis=0).reshape(5,5)




array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 2, 2, 2],
       [2, 2, 2, 3, 3],
       [3, 3, 3, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [178]:
#code
random_point=np.linspace(0,100,20,dtype=int).reshape(10,2)
random_point
point=np.array([2,3])
 
#calclute ecludien distance for each points 


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [179]:
#code here 
matrix=np.arange(0,336).reshape(6,7,8)
matrix[1:2,5:6,4:5]


array([[[100]]])

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [180]:
#Code here
#use of astype [The .astype() method is used to copy an existing NumPy array and cast its elements into a entirely new data type]
arr=np.array([1,2,3,4,-8,-10])
arr[-1::-1].astype(float)


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [181]:
#Code here
element_count=0
for i in arr:
    element_count +=1

element_count    

element_count=0
for i in np.nditer(arr):
    element_count +=1


element_count



6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [182]:
#Code here
#creating softmax functions
new_arr=np.array([10,2,3,4,5])
def softmax(value):
    e_x=np.exp(value-np.max(value))
    return e_x/e_x.sum()

softmax(new_arr)





array([9.89644319e-01, 3.31988684e-04, 9.02438806e-04, 2.45308301e-03,
       6.66817097e-03])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [183]:
#Coder here
#horizental and vertical stackiing
a1=np.arange(0,10).reshape(2,5)
a2=np.arange(10,20).reshape(2,5)
#vertical stacking 
np.vstack((a1,a2))

#horizental stacking 
np.hstack((a1,a2))





array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [184]:
#Code here
from datetime import date 
start=np.datetime64("2022-12-01")
end=np.datetime64('2022-12-07')

np.arange(start,end, dtype="datetime64[D]").reshape(2,3)


array([['2022-12-01', '2022-12-02', '2022-12-03'],
       ['2022-12-04', '2022-12-05', '2022-12-06']], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [185]:
#code here
#broad casting is used 
a3=np.arange(10,16).reshape(2,3)
rows_mean=np.mean(a3,axis=1,keepdims=True)
a3-rows_mean


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [186]:
#Code here
swap=np.arange(10,30).reshape(10,2)
swap[:,::-1] #flip according to cols 
swap[::-1,:] #flip according to rows 





array([[28, 29],
       [26, 27],
       [24, 25],
       [22, 23],
       [20, 21],
       [18, 19],
       [16, 17],
       [14, 15],
       [12, 13],
       [10, 11]])

###`Q-16:` Replace odd elements in arrays with -1.

In [202]:
#Code here
a4=np.arange(0,24).reshape(6,4)
a4[a4%2 !=0]=-1
a4

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1],
       [12, -1, 14, -1],
       [16, -1, 18, -1],
       [20, -1, 22, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [214]:
#Code here
a5=np.array([6,3,1,5,8])
a6=np.array([3,2,1,7,2])
res=np.where(a5>a6,a5,a6)
res


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [216]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1
def normalize(value):
    return (value-np.min(value))/(np.max(value)-np.min(value))

normalize(arr1)

array([[0.1705274 , 0.00558428, 0.09245088, 0.81592554, 0.67580145],
       [0.04819028, 0.74002068, 0.7459152 , 0.07362978, 0.87435367],
       [0.85480869, 0.56039297, 0.03474664, 0.72244054, 0.77828335],
       [0.06132368, 0.77073423, 0.72481903, 0.4697001 , 0.11220269],
       [0.3262668 , 0.94715615, 0.20682523, 0.93009307, 0.44053775],
       [0.64312306, 0.72574974, 1.        , 0.        , 0.0016546 ],
       [0.7459152 , 0.40351603, 0.25470527, 0.86566701, 0.12078594],
       [0.82647363, 0.99038263, 0.28872802, 0.81054809, 0.88955533]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [217]:
#Code here

def nth_largest(arr, n):
   
    if n > len(arr):
        raise ValueError("n cannot be larger than the length of the array")

 
    sorted_arr = np.sort(arr)

    
    return sorted_arr[-n]


nth_largest(arr,3)

np.int64(2)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here

a=np.array([1,2,3])
first_half=np.repeat(a,3)
first_half
second_half=np.tile(a,3)
second_half
np.hstack((first_half,second_half))


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])